# Generated by Django 5.0.7 on 2024-12-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshasathi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('session_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('schedule', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
