# Generated by Django 5.1.2 on 2024-12-31 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshasathi', '0006_safetyreport_mapmarking_safetyrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='safetyrating',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='safetyrating',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='safetyrating',
            name='review',
        ),
        migrations.AlterField(
            model_name='safetyrating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='safetyrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MapMarking',
        ),
    ]
