# Generated by Django 5.0.7 on 2024-12-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surakshasathi', '0006_category_safetytip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetytip',
            name='custom_icon',
        ),
    ]
