# Generated by Django 5.0.4 on 2025-01-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surakshasathi', '0007_remove_safetytip_custom_icon'),
        ('surakshasathi', '0007_rename_timestamp_safetyrating_created_at_and_more'),
    ]

    operations = [
    ]
