# Generated by Django 5.0.4 on 2025-01-03 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshasathi', '0008_merge_20250103_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('safety_status', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('unsafe', 'Unsafe')], default='moderate', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='safetytip',
            name='category',
        ),
        migrations.RemoveField(
            model_name='safetyrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='SafetyReport',
        ),
        migrations.AddField(
            model_name='users',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SafetyTip',
        ),
        migrations.DeleteModel(
            name='SafetyRating',
        ),
    ]
