# Generated by Django 5.1.2 on 2025-01-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshasathi', '0012_locationshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
