# Generated by Django 5.1.2 on 2025-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshasathi', '0013_users_is_active_users_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentMarkerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countincident', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarkerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
