# Generated by Django 5.0.4 on 2025-01-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surakshasathi', '0014_incidentmarkercount_markercount'),
    ]

    operations = [
    ]
